backend:
  name: github
  repo: timothyjellison/webdesignprompts

media_folder: static/assets

collections:
  - name: prompts
    label: Web Design Prompts
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }